package com.college.utils;

import com.zaxxer.hikari.HikariDataSource;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

/**
 * Change Tracker for the H2 fallback database.
 * 
 * When the application is running in H2 fallback mode, this class:
 * 1. Creates a _sync_journal table to track all data changes
 * 2. Installs H2 triggers on all application tables to capture INSERT/UPDATE/DELETE
 * 3. Provides methods to query pending (unsynced) changes
 * 4. Marks changes as synced after successful replay to PostgreSQL
 * 
 * The sync journal captures enough information to replay changes:
 * - Table name, operation type, primary key value
 * - Full row data as JSON for INSERT/UPDATE operations
 * - Timestamp for ordering
 */
public class ChangeTracker {

    private static volatile boolean trackingEnabled = false;

    /**
     * Tables that should be tracked for sync and replicated.
     * These are the main application tables (not system/meta tables).
     */
    public static final String[] TRACKED_TABLES = {
        "departments", "roles", "permissions", "role_permissions",
        "users", "students", "faculty", "courses", "student_courses",
        "attendance", "grades", "fee_categories", "fees", "fee_ledger",
        "books", "book_issues", "hostels", "rooms", "hostel_allocations",
        "hostel_attendance", "gate_passes", "events", "event_registrations",
        "clubs", "club_memberships", "club_announcements",
        "event_collaborators", "event_resources", "event_volunteers",
        "resource_categories", "course_syllabi", "learning_resources", "resource_tags",
        "student_feedback", "audit_logs", "announcements",
        "employees", "payroll", "timetable", "assignments", "submissions",
        "notifications", "book_requests", "complaints",
        "student_leaves", "staff_leaves", "system_settings",
        "placement_companies", "placement_drives", "placement_applications",
        "visitors", "visitor_logs",
        "community_posts", "community_comments", "community_likes",
        "event_budgets", "event_polls", "event_poll_votes",
        "wardens", "course_registrations", "enrollment_ids",
        "fee_payments", "scholarships", "scholarship_applications",
        "calendar_events"
    };

    /**
     * Initialize the change tracking system in H2.
     * Creates the sync journal table and installs triggers.
     * 
     * @param h2DataSource The H2 data source
     */
    public static void initialize(HikariDataSource h2DataSource) {
        Logger.info("[ChangeTracker] Initializing change tracking system...");

        try (Connection conn = h2DataSource.getConnection()) {
            createSyncJournalTable(conn);
            installTriggers(conn);
            Logger.info("[ChangeTracker] Change tracking system initialized successfully.");
        } catch (Exception e) {
            Logger.error("[ChangeTracker] Failed to initialize change tracking", e);
        }
    }

    /**
     * Create the sync journal table for tracking changes
     */
    private static void createSyncJournalTable(Connection conn) {
        try (Statement stmt = conn.createStatement()) {
            stmt.execute(
                "CREATE TABLE IF NOT EXISTS _sync_journal (" +
                "    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                "    table_name VARCHAR(100) NOT NULL," +
                "    operation VARCHAR(10) NOT NULL," +  // INSERT, UPDATE, DELETE
                "    primary_key_column VARCHAR(50) DEFAULT 'id'," +
                "    primary_key_value VARCHAR(100)," +
                "    row_data TEXT," +                    // JSON representation of the row
                "    old_row_data TEXT," +                // JSON of old row (for UPDATE/DELETE)
                "    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP," +
                "    synced BOOLEAN DEFAULT FALSE" +
                ")"
            );

            // Index for efficient sync queries
            stmt.execute(
                "CREATE INDEX IF NOT EXISTS idx_sync_journal_unsynced " +
                "ON _sync_journal (synced, created_at)"
            );

            Logger.info("[ChangeTracker] _sync_journal table created/verified.");

        } catch (Exception e) {
            Logger.error("[ChangeTracker] Failed to create _sync_journal table", e);
        }
    }

    /**
     * Install H2 triggers on all tracked tables.
     * Triggers fire on INSERT, UPDATE, DELETE and log changes to _sync_journal.
     */
    private static void installTriggers(Connection conn) {
        int installed = 0;

        for (String table : TRACKED_TABLES) {
            try {
                // Check if table exists before installing triggers
                if (!tableExists(conn, table)) {
                    continue;
                }

                // Install INSERT trigger
                installTrigger(conn, table, "INSERT");
                // Install UPDATE trigger
                installTrigger(conn, table, "UPDATE");
                // Install DELETE trigger
                installTrigger(conn, table, "DELETE");
                installed++;

            } catch (Exception e) {
                Logger.debug("[ChangeTracker] Could not install triggers for table '" + table + "': " + e.getMessage());
            }
        }

        Logger.info("[ChangeTracker] Triggers installed on " + installed + " tables.");
    }

    /**
     * Install a single trigger on a table for a specific operation
     */
    private static void installTrigger(Connection conn, String table, String operation) throws Exception {
        String triggerName = "_sync_trigger_" + table + "_" + operation.toLowerCase();

        try (Statement stmt = conn.createStatement()) {
            // Drop existing trigger if it exists
            stmt.execute("DROP TRIGGER IF EXISTS " + triggerName);

            // Create the trigger using H2's Java trigger mechanism
            String triggerSql = String.format(
                "CREATE TRIGGER %s AFTER %s ON %s FOR EACH ROW " +
                "CALL \"%s\"",
                triggerName, operation, table, SyncTrigger.class.getName()
            );

            stmt.execute(triggerSql);
        }
    }

    /**
     * Check if a table exists in the H2 database
     */
    private static boolean tableExists(Connection conn, String table) {
        try (ResultSet rs = conn.getMetaData().getTables(null, null, table.toUpperCase(), new String[]{"TABLE"})) {
            return rs.next();
        } catch (Exception e) {
            return false;
        }
    }

    // ─── Sync Query Methods ──────────────────────────────────────────────

    /**
     * Get all unsynced journal entries, ordered by creation time
     * 
     * @return List of SyncEntry objects representing pending changes
     */
    public static List<SyncEntry> getUnsyncedEntries() {
        List<SyncEntry> entries = new ArrayList<>();

        HikariDataSource h2Ds = DatabaseConnection.getH2DataSource();
        if (h2Ds == null || h2Ds.isClosed()) {
            return entries;
        }

        String sql = "SELECT id, table_name, operation, primary_key_column, primary_key_value, " +
                     "row_data, old_row_data, created_at " +
                     "FROM _sync_journal WHERE synced = FALSE ORDER BY created_at ASC, id ASC";

        try (Connection conn = h2Ds.getConnection();
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(sql)) {

            while (rs.next()) {
                SyncEntry entry = new SyncEntry();
                entry.id = rs.getLong("id");
                entry.tableName = rs.getString("table_name");
                entry.operation = rs.getString("operation");
                entry.primaryKeyColumn = rs.getString("primary_key_column");
                entry.primaryKeyValue = rs.getString("primary_key_value");
                entry.rowData = rs.getString("row_data");
                entry.oldRowData = rs.getString("old_row_data");
                entry.createdAt = rs.getTimestamp("created_at");
                entries.add(entry);
            }

        } catch (Exception e) {
            Logger.error("[ChangeTracker] Failed to read unsynced entries", e);
        }

        return entries;
    }

    /**
     * Mark specific journal entries as synced
     */
    public static void markAsSynced(List<Long> entryIds) {
        if (entryIds.isEmpty()) return;

        HikariDataSource h2Ds = DatabaseConnection.getH2DataSource();
        if (h2Ds == null || h2Ds.isClosed()) return;

        StringBuilder sql = new StringBuilder("UPDATE _sync_journal SET synced = TRUE WHERE id IN (");
        for (int i = 0; i < entryIds.size(); i++) {
            if (i > 0) sql.append(",");
            sql.append(entryIds.get(i));
        }
        sql.append(")");

        try (Connection conn = h2Ds.getConnection();
             Statement stmt = conn.createStatement()) {
            stmt.executeUpdate(sql.toString());
        } catch (Exception e) {
            Logger.error("[ChangeTracker] Failed to mark entries as synced", e);
        }
    }

    /**
     * Get count of pending (unsynced) changes
     */
    public static int getPendingChangeCount() {
        HikariDataSource h2Ds = DatabaseConnection.getH2DataSource();
        if (h2Ds == null || h2Ds.isClosed()) return 0;

        try (Connection conn = h2Ds.getConnection();
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery("SELECT COUNT(*) FROM _sync_journal WHERE synced = FALSE")) {
            if (rs.next()) {
                return rs.getInt(1);
            }
        } catch (Exception e) {
            Logger.debug("[ChangeTracker] Could not count pending changes: " + e.getMessage());
        }
        return 0;
    }

    /**
     * Clear all synced entries from the journal (cleanup)
     */
    public static void clearSyncedEntries() {
        HikariDataSource h2Ds = DatabaseConnection.getH2DataSource();
        if (h2Ds == null || h2Ds.isClosed()) return;

        try (Connection conn = h2Ds.getConnection();
             Statement stmt = conn.createStatement()) {
            int deleted = stmt.executeUpdate("DELETE FROM _sync_journal WHERE synced = TRUE");
            Logger.info("[ChangeTracker] Cleared " + deleted + " synced journal entries.");
        } catch (Exception e) {
            Logger.error("[ChangeTracker] Failed to clear synced entries", e);
        }
    }

    // ─── Tracking Control ────────────────────────────────────────────────

    /**
     * Enable or disable change tracking.
     * When disabled, triggers still fire but SyncTrigger skips logging.
     */
    public static void setTrackingEnabled(boolean enabled) {
        trackingEnabled = enabled;
        Logger.info("[ChangeTracker] Change tracking " + (enabled ? "ENABLED" : "DISABLED"));
    }

    /**
     * Check if change tracking is currently enabled
     */
    public static boolean isTrackingEnabled() {
        return trackingEnabled;
    }

    // ─── Inner Classes ───────────────────────────────────────────────────

    /**
     * Represents a single change entry in the sync journal
     */
    public static class SyncEntry {
        public long id;
        public String tableName;
        public String operation;       // INSERT, UPDATE, DELETE
        public String primaryKeyColumn;
        public String primaryKeyValue;
        public String rowData;         // JSON of new row data
        public String oldRowData;      // JSON of old row data (UPDATE/DELETE)
        public java.sql.Timestamp createdAt;

        @Override
        public String toString() {
            return String.format("[%s] %s on %s (PK=%s)", operation, tableName, primaryKeyValue, createdAt);
        }
    }
}
